nginx:
    image: nginx
    volumes:
        - /home/OnlineJudge/dockerfiles/oj_web_server/oj.conf:/etc/nginx/conf.d/default.conf
        - /home/upload:/upload
        - /home/OnlineJudge/static/release:/static
    links:
         - oj_web_server:oj_web_server
    ports:
        - "0.0.0.0:80:80"