redis:
    image: redis
    volumes:
        - /home/data/redis:/data
mysql:
    image: mysql
    volumes:
        - /home/data/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD={YOUR_PASSWORD}
oj_web_server:
    image: qduoj/oj_web_server
    volumes:
        - /home/OnlineJudge:/code
        - /home/test_case:/code/test_case
        - /home/upload:/code/upload
        - /home/log:/code/log
    links:
        - redis:redis
        - mysql:mysql
    ports:
        - "127.0.0.1:8080:8080"
    environment:
        - TZ=Asia/Shanghai
        - oj_env=server
        - MYSQL_ENV_MYSQL_USER=root

nginx:
    image: nginx:1.10.1
    volumes:
        - /home/OnlineJudge/dockerfiles/oj_web_server/oj.conf:/etc/nginx/conf.d/default.conf
        - /home/upload:/upload
        - /home/OnlineJudge/static/release:/static
    links:
         - oj_web_server:oj_web_server
    ports:
        - "0.0.0.0:80:80"